[project]
name = "kapa-recon"
version = "0.2.2"
description = "Reconstructor generation for the Keck KAPA AO System"
readme = "README.md"
authors = [
    { name = "Jesse Cranney", email = "jesse.cranney@anu.edu.au" }
]
requires-python = ">=3.13"
dependencies = [
    "devtools>=0.12.2",
    "ipython>=9.15.0",
    "matplotlib>=3.10.9",
    "numpy>=2.5.2",
    "pydantic>=2.13.4",
    "pyyaml>=6.0.3",
    "rao>=0.3.5",
    "scipy>=1.17.1",
    "scipy-stubs>=1.18.0.1",
    "taguchi>=1.2.2",
    "tqdm>=4.67.3",
]

[project.scripts]
fit-imat = "kapa_recon:fit_imat.main"
build-cmat = "kapa_recon:build_reconstructor.main"

[build-system]
requires = ["uv_build>=0.11.25,<0.12.0"]
build-backend = "uv_build"

